language: python
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27-1.11.X
  - TOXENV=py34-1.11.X
# for python 3.5 and 3.6, see https://github.com/travis-ci/travis-ci/issues/4794
# for python 3.7, see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.11.X
    - python: 3.6
      env: TOXENV=py36-1.11.X
    - python: 3.7
      env: TOXENV=py37-1.11.X
      dist: xenial
    - python: 3.5
      env: TOXENV=py35-2.1.X
    - python: 3.6
      env: TOXENV=py36-2.1.X
    - python: 3.7
      env: TOXENV=py37-2.1.X
      dist: xenial
    - python: 3.5
      env: TOXENV=py35-2.2.X
    - python: 3.6
      env: TOXENV=py36-2.2.X
    - python: 3.7
      env: TOXENV=py37-2.2.X
      dist: xenial

notifications:
  irc: "irc.freenode.org#django-compressor"
after_success:
  - pip install codecov
  - codecov
